"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from celery.schedules import crontab
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG') == 'True'

# ALLOWED_HOSTS qismiga o'zimiz bilgan IP ni qo'shib qo'yamiz
ALLOWED_HOSTS = ['157.173.124.216', 'testborbaza.uz', 'www.testborbaza.uz', '127.0.0.1', 'localhost']


CSRF_TRUSTED_ORIGINS = [
    'https://testborbaza.uz',
    'https://www.testborbaza.uz',
    'https://photokinetic-edris-bridleless.ngrok-free.dev',
    'https://*.ngrok-free.dev',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CORS_ALLOW_ALL_ORIGINS = True  # Mobileda turli tarmoqlardan kirganda muammo bo'lmasligi uchun
CORS_ALLOW_CREDENTIALS = True

# Ngrok HTTPS ishlatgani uchun bular True bo'lgani ma'qul
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# 'Lax' Telegram ichida ba'zan muammo qilishi mumkin, 
# shuning uchun sessiya yo'qolib qolmasligi uchun 'None' ni ham sinab ko'rish kerak
SESSION_COOKIE_SAMESITE = 'None' 
CSRF_COOKIE_SAMESITE = 'None'

# Har bir so'rovda sessiyani yangilab turish (siz yozganingizdek)
SESSION_SAVE_EVERY_REQUEST = True

# BU JUDA MUHIM: 
# SESSION_COOKIE_HTTPONLY ni False qilmang! 
# U True holatda turishi kerak (xavfsizlik uchun). 
# Muammo unga bog'liq emas.
SESSION_COOKIE_HTTPONLY = True



# Application definition

INSTALLED_APPS = [

    'jazzmin',


    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    

    'myapp_messages',  
    'accounts',
    'amaliyot',
    'fastapi',
    'widget_tweaks',
    'openpyxl',
    'rest_framework',
    'rest_framework_nested',
    'rest_framework.authtoken',
    'drf_spectacular',
    'corsheaders',
    'cryptography',
    'celery',
    'redis',
    'channels',
    'django_extensions',
    'mammoth',
    'xlrd',
    'pandas',
    

    
    
    
]


ASGI_APPLICATION = "core.asgi.application"


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', # 1. Sessiya boshida
    'corsheaders.middleware.CorsMiddleware',                 # 🔥 CORS endi shu yerda bo'lishi shart!
    'django.middleware.common.CommonMiddleware',             # 3. Common middleware
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware', 
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'testborbaza_db',
        'USER': 'testbor_user',
        'PASSWORD': 'JasurDev2026!',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py

# Login sahifasining haqiqiy manzili (Logingizga qarab)
LOGIN_URL = '/login/' 

# Login qilgandan keyin boradigan joy
LOGIN_REDIRECT_URL = '/dashboard/'

# Buni ham tekshirib qo'ying
REDIRECT_FIELD_NAME = 'next'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
}



API_KEY = 'a1b2c3d4e5f6'  


CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://127.0.0.1:5500",
    "http://localhost:5500",
]




MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_ROOT = BASE_DIR / "staticfiles"



# CLICK to‘lov tizimi sozlamalari
CLICK_MERCHANT_ID = "your_click_merchant_id"       # Merchant ID
CLICK_SERVICE_ID = "your_click_service_id"         # Servis ID
CLICK_SECRET_KEY = "your_click_secret_key"         # Secret key (maxfiy kalit)
CLICK_MERCHANT_USER_ID = "your_click_merchant_user_id"  # Merchant user ID
CLICK_RETURN_URL = "https://yourdomain.com/api/click/callback/"  # Callback URL


PAYME_MERCHANT_ID = "5f1e6a2b7e..."   # Payme'dan olingan ID
PAYME_MERCHANT_KEY = "a3x9s2d..."     # Authorization key (test uchun)
PAYME_URL = "https://checkout.test.paycom.uz/api"  # TEST MUHIT!!!
PAYME_CALLBACK_URL = "https://yourdomain.com/api/payme/callback/"

PAYME_CALLBACK_URL = "https://yourdomain.com/api/payment/callback/"
CLICK_CALLBACK_URL = "https://yourdomain.com/api/payment/callback/"




CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'


CELERY_BEAT_SCHEDULE = {
    'evaluate-expired-tests-every-minute': {
        'task': 'amaliyot.tasks.auto_evaluate_expired_tests',
        'schedule': crontab(),  
    },
}


STATIC_URL = '/static/'

STATICFILES_DIRS = [BASE_DIR / "static"]

STATIC_ROOT = BASE_DIR / "staticfiles"

SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_HTTPONLY = True

APPEND_SLASH = True

CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrf-token",
    "x-requested-with",
    "ngrok-skip-browser-warning", # Bu juda muhim!
]













